before_install: cd front-end
language: node_js
node_js:
  - '12'
dist: trusty
jobs:
  include:
    # ======== Parte del frontend ========
    - language: node_js
      node_js:  '12'

      warnings_are_errors: false

      cache:
        directories:
          - node_modules

      branches:
        only:
          - master

      before_install:
        - cd front-end

      before script:
        - npm install react-bootstrap
      script:
          - npm test
          - npm run build

      deploy:
        provider: heroku
        api_key: $APIKEYHEROKU
        app: social-distancing-restaurant

    # ======== Parte de Backend ========
    - language: node_js
      node_js:  '12'

      warnings_are_errors: false

      cache:
        directories:
          - node_modules

      branches:
        only:
          - master

      before_install:
        - cd back-end

      before_script:
        - npm install
      script:
          - node index.js &

      deploy:
        provider: heroku
        api_key: $APIKEYHEROKU
        app: s-d-r-backend
